/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:69c50273-7ddf-4188-9a3e-c4d88df8b631",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hmY6f733M",
    "aws_user_pools_web_client_id": "5bn3ck0oqj1ha821dg5edl9eph",
    "oauth": {}
};


export default awsmobile;
